# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('theme', models.CharField(db_index=True, max_length=50)),
                ('repository_url', models.URLField(blank=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('screenshot', models.URLField(blank=True, null=True)),
                ('downloads', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
            ],
        ),
    ]
