# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-downloads', '-stars']},
        ),
    ]
